### PR TITLE
add random extra expire time to redis cache to avoid hot key problem

### PR DESCRIPTION
**Pull request by liuhaozzu**
add random extra expire time to redis cache to avoid hot key problem

### CODE REVIEW

**Comment by areyouok** [comment]
I can't understand why you need add a random int to *expire*.

**Comment by liuhaozzu** [comment]
for example, there are 10000 request caching 10000 entries in redis at the same time, if we use a fixed expire time, they will expire at the same time and  then there will be a lot of cache miss at the same expire time. It'll cause some problem to the backend database. If we add a random expire time to each cached entry, they'll expire at different time, and the huge cache miss can be avoid.

**Comment by areyouok** [comment]
Before you think about *“they will expire at the same time and then there will be a lot of cache miss at the same expire time”*, you should first worry about *"there are 10000 requests caching 10000 entries in redis at the same time"*. Since db can't process 10000 requests at same time, the 10000 cache operations are not simultaneous.

If you has 10000 pre-load values, you can put them into cache with different *expire* only in pre-heat process. It's easy to implement.

In fact, this commit almost disable the *expire* attribute, users can't specify *expire* precisely. The real *expire* will not repect to what you set and may be infinity.

**Comment by liuhaozzu** [comment]
@areyouok ,thank you for your comments. I'll rethink this part.

**Pull request closed without merging**
